sudo: false
language: node_js
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - npm update
install:
  - npm install
node_js:
 - '10.0'
script:
  - npm test
dist: trusty
env:
  NODE_ENV=feature/travis jest --notify
